services:
  web:
    build:
      context: .
      dockerfile: php.dockerfile
      target: web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge

